unpackaged/main/default/objects/Option__c/Option__c.object-meta.xml
<CustomObject>
    <label>Option</label>
    <nameField>
        <displayFormat>OPT-{0000}</displayFormat>
        <label>Option Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Option__c/fields/Authorized_Login_Text__c.field-meta.xml
<CustomField>
    <fullName>Authorized_Login_Text__c</fullName>
    <label>Authorized Login Text</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Option__c/fields/Component_Active__c.field-meta.xml
<CustomField>
    <fullName>Component_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Component Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Option__c/fields/Component_Button_Name__c.field-meta.xml
<CustomField>
    <fullName>Component_Button_Name__c</fullName>
    <label>Component Button Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Option__c/fields/Component_Mode__c.field-meta.xml
<CustomField>
    <fullName>Component_Mode__c</fullName>
    <label>Component Mode</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Embeded</fullName>
            </value>
            <value>
                <fullName>On Button Press</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Option__c/fields/Component_Name__c.field-meta.xml
<CustomField>
    <fullName>Component_Name__c</fullName>
    <label>Component Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Option__c/fields/Component_Type__c.field-meta.xml
<CustomField>
    <fullName>Component_Type__c</fullName>
    <label>Component Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Screen Flow</fullName>
            </value>
            <value>
                <fullName>LWC</fullName>
            </value>
            <value>
                <fullName>Redirect Externally</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Option__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Center Section Text</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/Option__c/fields/Header__c.field-meta.xml
<CustomField>
    <fullName>Header__c</fullName>
    <label>Header</label>
    <length>2000</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/Option__c/fields/In_Option_Description__c.field-meta.xml
<CustomField>
    <fullName>In_Option_Description__c</fullName>
    <label>Option Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Option__c/fields/Login_Type__c.field-meta.xml
<CustomField>
    <fullName>Login_Type__c</fullName>
    <label>Login Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Authorized</fullName>
            </value>
            <value>
                <fullName>Unauthorized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Option__c/fields/Option__c.field-meta.xml
<CustomField>
    <fullName>Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Option</label>
    <referenceTo>Option__c</referenceTo>
    <relationshipLabel>Child Options</relationshipLabel>
    <relationshipName>Child_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Option__c/fields/Option_Name__c.field-meta.xml
<CustomField>
    <fullName>Option_Name__c</fullName>
    <label>Option Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Option__c/fields/Right_Section_Text__c.field-meta.xml
<CustomField>
    <fullName>Right_Section_Text__c</fullName>
    <label>Right Section Text</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/Option__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <label>Draft 📝</label>
            </value>
            <value>
                <fullName>Under Review</fullName>
                <label>Under Review 🔍</label>
            </value>
            <value>
                <fullName>Active</fullName>
                <label>Active ✅</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <label>Inactive 🚫</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Option__c/fields/Sub_Header__c.field-meta.xml
<CustomField>
    <fullName>Sub_Header__c</fullName>
    <label>Sub Header</label>
    <length>2000</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/classes/DFD_ServicesMenuControllerTest.cls
@isTest
public class DFD_ServicesMenuControllerTest {
    
    @isTest
    public static void testMethod1()
    {
        Option__c newOption = new Option__c();
        newOption.Authorized_Login_Text__c ='Test';
        newOption.Component_Active__c = true;
        newOption.Component_Button_Name__c='Test Button';
        newOption.Component_Mode__c = 'Embedded';
        newOption.Component_Name__c = 'Test Component';
        newOption.Component_Type__c = 'LWC';
        newOption.Description__c = 'Test Description';
        newOption.External_URL__c = 'https://google.com';
        newOption.Header__c = 'Test Header';
        newOption.In_Option_Description__c = 'Test';
        newOption.Login_Type__c = 'Authorized';
        newOption.Right_Section_Text__c = 'Test Service';
        newOption.Option_Name__c = 'Test Service';
        newOption.Status__c = 'Active';
        newOption.Sub_Header__c = 'True';
        Test.startTest();
        insert newOption;
        DFD_ServicesMenuController.getOptionsMap();
         DFD_ServicesMenuController.getUserLoginInfo();
        dfdTestLwcController.getOptionRecord(newOption.Id);
        dfdTestLwcController.createCase('Test','Test','Web','New','Low','Question');
         Test.stopTest();
    }

}