unpackaged/main/default/objects/Option__c/Option__c.object-meta.xml
<CustomObject>
    <label>Option</label>
    <nameField>
        <displayFormat>OPT-{0000}</displayFormat>
        <label>Option Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Option__c/fields/Option__c.field-meta.xml
<CustomField>
    <fullName>Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Option</label>
    <referenceTo>Option__c</referenceTo>
    <relationshipLabel>Child Options</relationshipLabel>
    <relationshipName>Child_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Option__c/fields/Option_Name__c.field-meta.xml
<CustomField>
    <fullName>Option_Name__c</fullName>
    <label>Option Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/dfdTestLwcController.cls
public without sharing class dfdTestLwcController {
    @AuraEnabled
    public static String createCase(String subject, String description, String origin,
                                    String status, String priority, String type)
    {
        Case cse = new Case();
        cse.Subject = subject;
        cse.Description = description;
        cse.Origin = origin;
        cse.Status = status;
        cse.Priority = priority;
        cse.Type = type;

        insert cse;
        Case cseNew = [SELECT id, CaseNumber FROM Case WHERE Id =:cse.Id];
        return cseNew.CaseNumber;

    }
    @AuraEnabled
    public static Option__c getOptionRecord(String recordId)
    {
        return [SELECT id,Option_Name__c FROM Option__c WHERE Id =:recordId];
    }

}