unpackaged/main/default/objects/DFD_Config__mdt/DFD_Config__mdt.object-meta.xml
<CustomObject>
    <label>DFD_Config</label>
    <pluralLabel>DFD_Configs</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/DFD_Config__mdt/fields/In_Option_Link_font_size__c.field-meta.xml
<CustomField>
    <fullName>In_Option_Link_font_size__c</fullName>
    <label>In-Option Link font size</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/DFD_Config__mdt/fields/Links_per_Option__c.field-meta.xml
<CustomField>
    <fullName>Links_per_Option__c</fullName>
    <label>Links per Option</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/DFD_Config__mdt/fields/Option_font_size__c.field-meta.xml
<CustomField>
    <fullName>Option_font_size__c</fullName>
    <label>Option font size</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/DFD_Config__mdt/fields/Options_per_row__c.field-meta.xml
<CustomField>
    <fullName>Options_per_row__c</fullName>
    <defaultValue>3</defaultValue>
    <label>Options per row</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/DFD_Config__mdt/fields/Root_Option_RecordId__c.field-meta.xml
<CustomField>
    <fullName>Root_Option_RecordId__c</fullName>
    <label>Root Option RecordId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Option__c/Option__c.object-meta.xml
<CustomObject>
    <label>Option</label>
    <nameField>
        <displayFormat>OPT-{0000}</displayFormat>
        <label>Option Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Option__c/fields/Authorized_Login_Text__c.field-meta.xml
<CustomField>
    <fullName>Authorized_Login_Text__c</fullName>
    <label>Authorized Login Text</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Option__c/fields/Component_Active__c.field-meta.xml
<CustomField>
    <fullName>Component_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Component Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Option__c/fields/Component_Button_Name__c.field-meta.xml
<CustomField>
    <fullName>Component_Button_Name__c</fullName>
    <label>Component Button Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Option__c/fields/Component_Mode__c.field-meta.xml
<CustomField>
    <fullName>Component_Mode__c</fullName>
    <label>Component Mode</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Embeded</fullName>
            </value>
            <value>
                <fullName>On Button Press</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Option__c/fields/Component_Name__c.field-meta.xml
<CustomField>
    <fullName>Component_Name__c</fullName>
    <label>Component Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Option__c/fields/Component_Type__c.field-meta.xml
<CustomField>
    <fullName>Component_Type__c</fullName>
    <label>Component Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Screen Flow</fullName>
            </value>
            <value>
                <fullName>LWC</fullName>
            </value>
            <value>
                <fullName>Redirect Externally</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Option__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Center Section Text</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/Option__c/fields/Header__c.field-meta.xml
<CustomField>
    <fullName>Header__c</fullName>
    <label>Header</label>
    <length>2000</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/Option__c/fields/In_Option_Description__c.field-meta.xml
<CustomField>
    <fullName>In_Option_Description__c</fullName>
    <label>Option Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Option__c/fields/Login_Type__c.field-meta.xml
<CustomField>
    <fullName>Login_Type__c</fullName>
    <label>Login Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Authorized</fullName>
            </value>
            <value>
                <fullName>Unauthorized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Option__c/fields/Option__c.field-meta.xml
<CustomField>
    <fullName>Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Option</label>
    <referenceTo>Option__c</referenceTo>
    <relationshipLabel>Child Options</relationshipLabel>
    <relationshipName>Child_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Option__c/fields/Option_Name__c.field-meta.xml
<CustomField>
    <fullName>Option_Name__c</fullName>
    <label>Option Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Option__c/fields/Right_Section_Text__c.field-meta.xml
<CustomField>
    <fullName>Right_Section_Text__c</fullName>
    <label>Right Section Text</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/Option__c/fields/Sub_Header__c.field-meta.xml
<CustomField>
    <fullName>Sub_Header__c</fullName>
    <label>Sub Header</label>
    <length>2000</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/classes/DFD_ServicesMenuController.cls
/**
--------------------------------------------------------------------------------------------------------------------------------------------
Name                  : DFD_ServicesMenuController
Created By            : Ribanshu@Adpat-iq
Created Version       : V1.00
Description           : Apex contoller for servicesMenu LWC component
---------------------------------------------------------------------------------------------------------------------------------------------    
___________________________________________________________________________Change Log_________________________________________________________________________________________________________

Modified by              Version         Change Date         Purpose
______________________________________________________________________________________________________________________________________________________________________________________________
**/

public with sharing class  DFD_ServicesMenuController {
    @AuraEnabled
    //public static Map<Integer, List<Option__c>> getOptionsMap(Id rootRecordId)
    public static ResultWrapper getOptionsMap()
    {
        //Map<Integer, List<Option__c>> optionsMap = new Map<Integer, List<Option__c>>();
        //Map<String,List<Option__c>> optionsMap2 = new Map<String,List<Option__c>>();
        //Option__c rootRecord = new Option__c();
        ResultWrapper resWrap = new ResultWrapper();

       /* List<DFD_Config__mdt> dfdConfigs = DFD_Config__mdt.getAll().values();

        if(dfdConfigs[0].Root_Option_RecordId__c != NULL)
        {
            rootRecord = [SELECT Id,Name,Header__c,Sub_Header__c,In_Option_Description__c,Description__c,Option_Name__c,
                          Right_Section_Text__c,Component_Type__c,Component_Mode__c,Component_Name__c,Component_Active__c,
                          Component_Button_Name__c
                          FROM Option__c 
                          WHERE Id =:dfdConfigs[0].Root_Option_RecordId__c];
        }

        optionsMap.put(0,new list<Option__c>{rootRecord});
        
        Map<Id,Option__c> childOptionsMap = new Map<Id,Option__c>([SELECT Id,Name,Header__c,Sub_Header__c,In_Option_Description__c,Description__c,Right_Section_Text__c,
                                                                   Option_Name__c,Option__c,Component_Type__c,Component_Mode__c,Component_Name__c,Component_Active__c,
                                                                   Component_Button_Name__c
                                                                   FROM Option__c 
                                                                   WHERE id != :rootRecord.Id]); */
        List<Option__c> optionRecords = [SELECT Id,Name,Header__c,Sub_Header__c,In_Option_Description__c,Description__c,Right_Section_Text__c,
                                        Option_Name__c,Option__c,Component_Type__c,Component_Mode__c,Component_Name__c,Component_Active__c,
                                        Component_Button_Name__c,Login_Type__c,Authorized_Login_Text__c
                                        FROM Option__c];

        resWrap.optionRecords = optionRecords;

        List<DFD_Config__mdt> dfdConfigs = DFD_Config__mdt.getAll().values();
        if(dfdConfigs.size()>0)
        {
            resWrap.optionsPerRow = dfdConfigs[0].Options_per_row__c;
            resWrap.linksPerOption = dfdConfigs[0].Links_per_Option__c;
            resWrap.optionLinkFontSize = dfdConfigs[0].In_Option_Link_font_size__c;
            resWrap.optionFontSize = dfdConfigs[0].Option_font_size__c;
            resWrap.rootRecordId = dfdConfigs[0].Root_Option_RecordId__c;
        }   
        return resWrap;
    }
    @AuraEnabled
    public static UserLoginWrapper getUserLoginInfo()
    {

        // UserInfo.getUserName();0DBQ10000000zQ5OAI
        //Id communityId = Network.getNetworkId();isGuestUser()
       // return Network.getLoginUrl(Network.getNetworkId());
       UserLoginWrapper usrWrap = new UserLoginWrapper();
       if(Auth.CommunitiesUtil.isGuestUser())
       {
           usrWrap.isGuestUser = true;
           usrWrap.loginURL = Network.getLoginUrl(Network.getNetworkId());
       }
       else
       {
           usrWrap.isGuestUser = false;
       }
        return usrWrap;
        //return Network.getNetworkId();
    }

    public class ResultWrapper
    {
        @AuraEnabled public String rootRecordId {get; set;}
        @AuraEnabled public Decimal optionsPerRow {get; set;}
        @AuraEnabled public Decimal linksPerOption {get; set;}
        @AuraEnabled public Decimal optionLinkFontSize {get; set;}
        @AuraEnabled public Decimal optionFontSize {get; set;}
        @AuraEnabled public List<Option__c> optionRecords {get; set;}
    }

    public class UserLoginWrapper
    {
        @AuraEnabled public String loginURL {get; set;}
        @AuraEnabled public Boolean isGuestUser {get; set;}
    }    
}